### ISSUE TITLE
Won't build on Windows

### ISSUE THREAD

**Issue by SuperGameCube** [zeta0134/pikmin-nds#4]
I've been trying to get this to build on Windows for a few hours now, and with no luck.
As it turns out Python is required to build this, which is not stated for whatever reason.
Though I have attempted to install hy, I just can't get it to work.
http://prntscr.com/c6sczl

A pre-compiled version of something like this would be nice.

**Comment by cromo** [comment]
The build instructions in the readme are a little out of date. We use docker to perform the build now because we needed to package specific versions of python, specific library versions that had to be installed system-wide that aren't available as packages on PyPI, a specific version of Blender so that the API doesn't change out underneath us for model conversion, etc.

As for pre-compiled versions, we're not doing for two reasons:

1. The project is nowhere near being an actual game yet; it's just a collection of game mechanics right now. You can't win or lose. There's not much more to it yet than can be seen in the imgur album. As such, we don't want to make an official release build just yet.
2. We don't have nightly builds or continuous integration set up yet and manually rebuilding and uploading every change is a bit of a pain. Getting something like this set up is on the todo list, but it hasn't been done yet.

Sorry for the inconvenience. If you really want a binary to mess around with, we can look into getting a build for you, and maybe simultaneously check CI builds off our list.

**Comment by SuperGameCube** [comment]
I see, thank you for the reply. Yes, I would love to mess around with it, having a build would be nice.

**Comment by cromo** [comment]
I'll see about getting CI stuff set up this weekend. I would've started on it earlier this week, but I'm waiting on a part to come in to repair my primary desktop computer at home. If nothing else, I'll get a build for you and update the build instructions in the readme.

**Comment by SuperGameCube** [comment]
Yes, thank you, I await eagerly.

**Comment by cromo** [comment]
CI is now set up through Travis CI and the automatic builds are linked in the README.

**Comment by zeta0134** [comment]
Windows will never be a supported platform for direct builds becasue quite frankly, I don't use Windows for development and don't have the time to support it. The project uses Docker to build though, so if you install docker, navigate to the project folder, and issue ./build.sh (within docker's VM on Windows platforms) it should run through the whole process.

On the bright side, we just added Continuous Integration to the project, which causes new builds to be generated automatically whenever changes are pushed to Github. If you just want to test out the demo, check those out here: http://pikmin-ds.nicholasflynt.com/

(That link is very likely to change, keep an eye on the README.md for updates.)

**Comment by SuperGameCube** [comment]
Thank you!
